import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadConfig, type LoadConfigOptions } from "./config.js";
import { readVault } from "./vault.js";

export function runIndex(options: LoadConfigOptions = {}) {
  const config = loadConfig(options);
  const { notes } = readVault(config.vaultDir);
  const rows = [...notes.values()].sort((a, b) => {
    if (a.id === "root") return -1;
    if (b.id === "root") return 1;
    return a.id.localeCompare(b.id);
  });
  const outFile = join(config.vaultDir, config.index.file);
  const lines = [
    "<!-- AUTOGENERATED by @madebywild/semantic-layer. Do not edit by hand. -->",
    "",
    "# Vault hierarchy",
    "",
    "Agents: read this file first, then load notes by id.",
    "",
    ...rows.map((note) => {
      const depth = note.id === "root" ? 0 : note.id.split(".").length - 1;
      const status = note.fm.status === "active" ? "" : ` (${note.fm.status})`;
      return `${"  ".repeat(depth)}- **${note.id}**${status} - ${note.fm.title}. ${note.fm.desc}`;
    }),
  ];
  writeFileSync(outFile, `${lines.join("\n")}\n`);
  return { outFile, noteCount: rows.length };
}
