import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { runIndex } from "../../../../packages/semantic-layer/src/index-vault.js";
import { createTempVault } from "../../../helpers.js";

function validNoteMd(
  id: string,
  title = id,
  desc = "Test note.",
  status = "active",
  body = "",
): string {
  return `---\nid: ${id}\ntitle: ${title}\ndesc: ${desc}\nstatus: ${status}\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\n---\n\n${body}`;
}

describe("runIndex", () => {
  it("generates HIERARCHY.md with root first", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/beta.md": validNoteMd("beta"),
      "vault/alpha.md": validNoteMd("alpha"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha, beta]\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      expect(result.noteCount).toBe(3);

      const content = readFileSync(result.outFile, "utf8");
      const lines = content.split("\n");
      // Root should come first
      expect(lines.find((l) => l.includes("**root**"))).toBeDefined();
      // Alpha and beta should be sorted alphabetically
      const alphaIdx = lines.findIndex((l) => l.includes("**alpha**"));
      const betaIdx = lines.findIndex((l) => l.includes("**beta**"));
      expect(alphaIdx).toBeLessThan(betaIdx);
    } finally {
      tv.cleanup();
    }
  });

  it("indents based on dot depth", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/parent.md": validNoteMd("parent"),
      "vault/parent.child.md": validNoteMd("parent.child"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [parent]\n",
      "vault/parent.schema.yml":
        "version: 1\nschemas:\n  - id: parent\n    parent: root\n    namespace: true\n    children: []\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      const content = readFileSync(result.outFile, "utf8");
      const lines = content.split("\n");

      const parentLine = lines.find((l) => l.includes("**parent**") && !l.includes("parent.child"));
      const childLine = lines.find((l) => l.includes("**parent.child**"));

      expect(parentLine).toBeDefined();
      expect(childLine).toBeDefined();
      // child should have more indentation than parent
      expect(childLine?.indexOf("-")).toBeGreaterThan(parentLine?.indexOf("-"));
    } finally {
      tv.cleanup();
    }
  });

  it("appends status marker for non-active notes", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/deprecated.md": validNoteMd("deprecated", "Deprecated", "Old note.", "deprecated"),
      "vault/draft.md": validNoteMd("draft", "Draft", "New note.", "draft"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [deprecated, draft]\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      const content = readFileSync(result.outFile, "utf8");

      expect(content).toContain("(deprecated)");
      expect(content).toContain("(draft)");
    } finally {
      tv.cleanup();
    }
  });

  it("omits status marker for active notes", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      const content = readFileSync(result.outFile, "utf8");

      // Active notes should not have a parenthetical status
      const rootLine = content.split("\n").find((l) => l.includes("**root**"));
      expect(rootLine).toBeDefined();
      expect(rootLine?.includes("(active)")).toBe(false);
    } finally {
      tv.cleanup();
    }
  });

  it("includes auto-generated header comment", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      const content = readFileSync(result.outFile, "utf8");
      expect(content).toContain("AUTOGENERATED");
      expect(content).toContain("Do not edit by hand");
    } finally {
      tv.cleanup();
    }
  });

  it("includes section headers", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      const content = readFileSync(result.outFile, "utf8");
      expect(content).toContain("# Vault hierarchy");
      expect(content).toContain("Agents: read this file first");
    } finally {
      tv.cleanup();
    }
  });

  it("returns outFile and noteCount", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = runIndex({ cwd: tv.dir });
      expect(result.outFile).toContain("HIERARCHY.md");
      expect(result.noteCount).toBe(1);
    } finally {
      tv.cleanup();
    }
  });

  it("overwrites existing HIERARCHY.md on second run", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/alpha.md": validNoteMd("alpha"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha]\n",
    });

    try {
      const result1 = runIndex({ cwd: tv.dir });
      expect(result1.noteCount).toBe(2);
      const content1 = readFileSync(result1.outFile, "utf8");

      // Add another note
      writeFileSync(join(tv.vaultDir, "beta.md"), validNoteMd("beta"));
      writeFileSync(
        join(tv.vaultDir, "root.schema.yml"),
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha, beta]\n",
      );

      const result2 = runIndex({ cwd: tv.dir });
      expect(result2.noteCount).toBe(3);
      const content2 = readFileSync(result2.outFile, "utf8");
      expect(content2).not.toBe(content1);
      expect(content2).toContain("**beta**");
    } finally {
      tv.cleanup();
    }
  });
});
