import { describe, expect, it } from "vitest";
import { readVault } from "../../../../packages/semantic-layer/src/vault.js";
import { createTempVault } from "../../../helpers.js";

function validNoteMd(id: string, title = id, body = `# ${title}\n`): string {
  return `---\nid: ${id}\ntitle: ${title}\ndesc: Test note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\n---\n\n${body}`;
}

describe("readVault", () => {
  it("reads a vault with markdown files", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/alpha.md": validNoteMd("alpha"),
    });

    try {
      const { notes } = readVault(tv.vaultDir);
      expect(notes.size).toBe(2);
      expect(notes.has("root")).toBe(true);
      expect(notes.has("alpha")).toBe(true);
      expect(notes.get("root")?.fm.title).toBe("root");
    } finally {
      tv.cleanup();
    }
  });

  it("skips HIERARCHY.md", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/HIERARCHY.md": "<!-- autogenerated -->\n# Vault\n- root\n",
    });

    try {
      const { notes } = readVault(tv.vaultDir);
      expect(notes.has("root")).toBe(true);
      expect(notes.has("HIERARCHY")).toBe(false);
    } finally {
      tv.cleanup();
    }
  });

  it("reads schema files", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const { schemas } = readVault(tv.vaultDir);
      expect(schemas.has("root")).toBe(true);
      expect(schemas.get("root")?.schemas[0]?.id).toBe("root");
    } finally {
      tv.cleanup();
    }
  });

  it("skips non-markdown, non-schema files", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/readme.txt": "ignore me",
      "vault/image.png": "not a real png",
    });

    try {
      const { notes, schemas } = readVault(tv.vaultDir);
      expect(notes.size).toBe(1);
      expect(schemas.size).toBe(0);
    } finally {
      tv.cleanup();
    }
  });

  it("returns empty maps for non-existent directory", () => {
    const { notes, schemas } = readVault("/nonexistent/path/that/does/not/exist");
    expect(notes.size).toBe(0);
    expect(schemas.size).toBe(0);
  });

  it("extracts and slugs headings", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root", "Root", "## My Section\n\n### Another Heading\n"),
    });

    try {
      const { notes } = readVault(tv.vaultDir);
      const root = notes.get("root");
      if (!root) throw new Error("expected root note");
      expect(root.headings.has("my-section")).toBe(true);
      expect(root.headings.has("another-heading")).toBe(true);
    } finally {
      tv.cleanup();
    }
  });

  it("parses frontmatter correctly", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
    });

    try {
      const { notes } = readVault(tv.vaultDir);
      const root = notes.get("root");
      if (!root) throw new Error("expected root note");
      expect(root.fm.id).toBe("root");
      expect(root.fm.title).toBe("root");
      expect(root.fm.desc).toBe("Test note.");
      expect(root.fm.status).toBe("active");
      expect(root.fm.owner).toBe("tester@example.com");
      // gray-matter parses unquoted dates as Date objects
      const lastVerified =
        root.fm.last_verified instanceof Date
          ? root.fm.last_verified.toISOString().slice(0, 10)
          : root.fm.last_verified;
      expect(lastVerified).toBe("2026-05-13");
      expect(root.fm.ttl_days).toBe(365);
    } finally {
      tv.cleanup();
    }
  });

  it("reads body content", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root", "Root", "## My Section\n\nSome text here.\n"),
    });

    try {
      const { notes } = readVault(tv.vaultDir);
      const root = notes.get("root");
      if (!root) throw new Error("expected root note");
      expect(root.body).toContain("## My Section");
      expect(root.body).toContain("Some text here.");
    } finally {
      tv.cleanup();
    }
  });

  it("handles .schema.yaml extension", () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yaml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const { schemas } = readVault(tv.vaultDir);
      expect(schemas.has("root")).toBe(true);
    } finally {
      tv.cleanup();
    }
  });
});
