import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { runIndex } from "../../../../packages/semantic-layer/src/commands/index.js";
import { loadConfig } from "../../../../packages/semantic-layer/src/config.js";
import { withConnectionForConfig } from "../../../../packages/semantic-layer/src/db/connection.js";
import { createFakeEmbedder, createTempVault } from "../../../helpers.js";

function validNoteMd(
  id: string,
  title = id,
  desc = "Test note.",
  status = "active",
  body = "",
): string {
  return `---\nid: ${id}\ntitle: ${title}\ndesc: ${desc}\nstatus: ${status}\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\n---\n\n${body}`;
}

describe("runIndex", () => {
  it("generates HIERARCHY.md with root first", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/beta.md": validNoteMd("beta"),
      "vault/alpha.md": validNoteMd("alpha"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha, beta]\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      expect(result.noteCount).toBe(3);

      const content = readFileSync(result.outFile, "utf8");
      const lines = content.split("\n");
      // Root should come first
      expect(lines.find((l) => l.includes("**root**"))).toBeDefined();
      // Alpha and beta should be sorted alphabetically
      const alphaIdx = lines.findIndex((l) => l.includes("**alpha**"));
      const betaIdx = lines.findIndex((l) => l.includes("**beta**"));
      expect(alphaIdx).toBeLessThan(betaIdx);
    } finally {
      tv.cleanup();
    }
  });

  it("indents based on dot depth", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/parent.md": validNoteMd("parent"),
      "vault/parent.child.md": validNoteMd("parent.child"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [parent]\n",
      "vault/parent.schema.yml":
        "version: 1\nschemas:\n  - id: parent\n    parent: root\n    namespace: true\n    children: []\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const content = readFileSync(result.outFile, "utf8");
      const lines = content.split("\n");

      const parentLine = lines.find((l) => l.includes("**parent**") && !l.includes("parent.child"));
      const childLine = lines.find((l) => l.includes("**parent.child**"));

      expect(parentLine).toBeDefined();
      expect(childLine).toBeDefined();
      // child should have more indentation than parent
      expect(childLine?.indexOf("-")).toBeGreaterThan(parentLine?.indexOf("-"));
    } finally {
      tv.cleanup();
    }
  });

  it("appends status marker for non-active notes", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/deprecated.md": validNoteMd("deprecated", "Deprecated", "Old note.", "deprecated"),
      "vault/draft.md": validNoteMd("draft", "Draft", "New note.", "draft"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [deprecated, draft]\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const content = readFileSync(result.outFile, "utf8");

      expect(content).toContain("(deprecated)");
      expect(content).toContain("(draft)");
    } finally {
      tv.cleanup();
    }
  });

  it("omits status marker for active notes", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const content = readFileSync(result.outFile, "utf8");

      // Active notes should not have a parenthetical status
      const rootLine = content.split("\n").find((l) => l.includes("**root**"));
      expect(rootLine).toBeDefined();
      expect(rootLine?.includes("(active)")).toBe(false);
    } finally {
      tv.cleanup();
    }
  });

  it("includes auto-generated header comment", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const content = readFileSync(result.outFile, "utf8");
      expect(content).toContain("AUTOGENERATED");
      expect(content).toContain("Do not edit by hand");
    } finally {
      tv.cleanup();
    }
  });

  it("includes section headers", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const content = readFileSync(result.outFile, "utf8");
      expect(content).toContain("# Vault hierarchy");
      expect(content).toContain("Agents: read this file first");
    } finally {
      tv.cleanup();
    }
  });

  it("returns outFile, codeRefsFile, dbFile and metaFile", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      expect(result.outFile).toContain("HIERARCHY.md");
      expect(result.codeRefsFile).toContain(".semantic-layer/code-refs.json");
      expect(result.db?.dbFile).toContain(".semantic-layer/vault.lbug");
      expect(result.db?.metaFile).toContain(".semantic-layer/vault.lbug.meta.json");
      expect(result.noteCount).toBe(1);
    } finally {
      tv.cleanup();
    }
  });

  it("writes an empty code refs sidecar when no notes reference code", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const sidecar = JSON.parse(readFileSync(result.codeRefsFile, "utf8")) as {
        schema_version: number;
        refs: unknown[];
      };
      expect(sidecar).toEqual({ schema_version: 1, refs: [] });
    } finally {
      tv.cleanup();
    }
  });

  it("writes sorted resolved code ref metadata", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/zeta.md": `---\nid: zeta\ntitle: Zeta\ndesc: Zeta note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  - file: src/mod.ts\n    symbol: zed\n---\n\nZeta.`,
      "vault/alpha.md": `---\nid: alpha\ntitle: Alpha\ndesc: Alpha note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  - file: src/mod.ts\n    symbol: alpha\n---\n\nAlpha.`,
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha, zeta]\n",
      "src/mod.ts": ["export function zed() { return 1; }", "export const alpha = 1;"].join("\n"),
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const sidecar = JSON.parse(readFileSync(result.codeRefsFile, "utf8")) as {
        schema_version: number;
        refs: Array<{
          note_id: string;
          ref: { file: string; symbol: string };
          kind: string;
          namespaces: string[];
          line: number;
          column: number;
          declarations: Array<{ file: string; kind: string; line: number; column: number }>;
        }>;
      };

      expect(sidecar.schema_version).toBe(1);
      expect(sidecar.refs.map((ref) => ref.note_id)).toEqual(["alpha", "zeta"]);
      expect(sidecar.refs[0]).toMatchObject({
        note_id: "alpha",
        ref: { file: "src/mod.ts", symbol: "alpha" },
        kind: "const",
        namespaces: ["value"],
        line: 2,
        column: 14,
        declarations: [{ file: "src/mod.ts", kind: "const", line: 2, column: 14 }],
      });
      expect(sidecar.refs[1]).toMatchObject({
        note_id: "zeta",
        kind: "function",
        line: 1,
        column: 17,
      });
    } finally {
      tv.cleanup();
    }
  });

  it("uses the referenced file location for import alias sidecar metadata", async () => {
    const tv = createTempVault({
      "vault/root.md": `---\nid: root\ntitle: Root\ndesc: Root note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  - file: src/consumer.ts\n    symbol: aliasedTarget\n---\n\nRoot.`,
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
      "src/target.ts": "export function target() { return 1; }\n",
      "src/consumer.ts": 'import { target as aliasedTarget } from "./target.js";\n',
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const sidecar = JSON.parse(readFileSync(result.codeRefsFile, "utf8")) as {
        refs: Array<{
          kind: string;
          line: number;
          column: number;
          declarations: Array<{ file: string; kind: string; line: number; column: number }>;
        }>;
      };
      expect(sidecar.refs[0]).toMatchObject({
        kind: "function",
        line: 1,
        column: 20,
        declarations: [
          { file: "src/consumer.ts", kind: "import", line: 1, column: 20 },
          { file: "src/target.ts", kind: "function", line: 1, column: 17 },
        ],
      });
    } finally {
      tv.cleanup();
    }
  });

  it("does not leak external declaration paths into generated code ref metadata", async () => {
    const tv = createTempVault({
      "vault/root.md": `---\nid: root\ntitle: Root\ndesc: Root note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  - file: src/fs.ts\n    symbol: readFileSync\n    kind: import\n---\n\nRoot.`,
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
      "src/fs.ts": 'import { readFileSync } from "node:fs";\n',
    });

    try {
      const result = await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      const sidecar = JSON.parse(readFileSync(result.codeRefsFile, "utf8")) as {
        refs: Array<{ declarations: Array<{ file: string }> }>;
      };
      expect(sidecar.refs[0]?.declarations).toEqual([
        { file: "src/fs.ts", kind: "import", line: 1, column: 10 },
      ]);
    } finally {
      tv.cleanup();
    }
  });

  it("does not overwrite generated files when code ref metadata cannot be generated", async () => {
    const tv = createTempVault({
      "vault/root.md": `---\nid: root\ntitle: Root\ndesc: Root note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  - file: src/mod.ts\n    symbol: missing\n---\n\nRoot.`,
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
      "vault/HIERARCHY.md": "existing hierarchy\n",
      "src/mod.ts": "export const present = 1;\n",
    });

    try {
      await expect(runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() })).rejects.toThrow(
        "code_ref src/mod.ts#missing not found",
      );
      expect(readFileSync(join(tv.vaultDir, "HIERARCHY.md"), "utf8")).toBe("existing hierarchy\n");
      expect(existsSync(join(tv.vaultDir, ".semantic-layer/code-refs.json"))).toBe(false);
    } finally {
      tv.cleanup();
    }
  });

  it("reports malformed code_refs frontmatter before resolving during index", async () => {
    const tv = createTempVault({
      "vault/root.md": `---\nid: root\ntitle: Root\ndesc: Root note.\nstatus: active\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  file: src/mod.ts\n  symbol: missing\n---\n\nRoot.`,
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
      "src/mod.ts": "export const present = 1;\n",
    });

    try {
      await expect(runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() })).rejects.toThrow(
        "frontmatter.code_refs",
      );
    } finally {
      tv.cleanup();
    }
  });

  it("does not resolve code refs from notes with invalid frontmatter during index", async () => {
    const tv = createTempVault({
      "vault/root.md": `---\nid: root\ntitle: Root\ndesc: Root note.\nstatus: invalid\nowner: tester@example.com\nlast_verified: 2026-05-13\nttl_days: 365\ncode_refs:\n  - file: src/missing.ts\n    symbol: missing\n---\n\nRoot.`,
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
    });

    try {
      let message = "";
      try {
        await runIndex({ cwd: tv.dir, embedder: createFakeEmbedder() });
      } catch (error) {
        message = error instanceof Error ? error.message : String(error);
      }
      expect(message).toContain("frontmatter.status");
      expect(message).not.toContain("code_ref file does not exist");
    } finally {
      tv.cleanup();
    }
  });

  it("overwrites existing HIERARCHY.md on second run", async () => {
    const tv = createTempVault({
      "vault/root.md": validNoteMd("root"),
      "vault/alpha.md": validNoteMd("alpha"),
      "vault/root.schema.yml":
        "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha]\n",
    });

    try {
      const config = loadConfig({ cwd: tv.dir });
      const embedder = createFakeEmbedder();

      // Reuse a single LadybugDB connection across both runs to avoid the WAL checkpoint race that
      // intermittently corrupts rapid open/close cycles in the same process.
      await withConnectionForConfig(config, async (conn) => {
        const result1 = await runIndex({ cwd: tv.dir, embedder, connection: conn });
        expect(result1.noteCount).toBe(2);
        const content1 = readFileSync(result1.outFile, "utf8");

        // Add another note
        writeFileSync(join(tv.vaultDir, "beta.md"), validNoteMd("beta"));
        writeFileSync(
          join(tv.vaultDir, "root.schema.yml"),
          "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha, beta]\n",
        );

        const result2 = await runIndex({ cwd: tv.dir, embedder, connection: conn });
        expect(result2.noteCount).toBe(3);
        const content2 = readFileSync(result2.outFile, "utf8");
        expect(content2).not.toBe(content1);
        expect(content2).toContain("**beta**");
      });
    } finally {
      tv.cleanup();
    }
  });

  it("writes sidecars without building the database when search is disabled", async () => {
    const tv = createTempVault(
      {
        "vault/root.md": validNoteMd("root"),
        "vault/alpha.md": validNoteMd("alpha"),
        "vault/root.schema.yml":
          "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: [alpha]\n",
      },
      { search: { enabled: false } },
    );

    try {
      // No embedder needed at all: the whole DB path must be skipped.
      const result = await runIndex({ cwd: tv.dir });
      expect(result.db).toBeUndefined();
      expect(result.noteCount).toBe(2);

      const content = readFileSync(result.outFile, "utf8");
      expect(content).toContain("**root**");
      expect(content).toContain("**alpha**");
      expect(existsSync(result.codeRefsFile)).toBe(true);
      expect(
        existsSync(join(tv.vaultDir, ".semantic-layer", "vault.lbug")),
        "no LadybugDB file may be created",
      ).toBe(false);
    } finally {
      tv.cleanup();
    }
  });

  it("reports frontmatter errors instead of writing sidecars when search is disabled", async () => {
    const tv = createTempVault(
      {
        "vault/root.md": validNoteMd("root").replace("title: root", 'title: ""'),
        "vault/root.schema.yml":
          "version: 1\nschemas:\n  - id: root\n    parent: root\n    children: []\n",
      },
      { search: { enabled: false } },
    );

    try {
      await expect(runIndex({ cwd: tv.dir })).rejects.toThrow(/frontmatter\.title/);
      expect(existsSync(join(tv.vaultDir, "HIERARCHY.md"))).toBe(false);
    } finally {
      tv.cleanup();
    }
  });
});
