import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  buildCodeRefsIndex,
  collectCodeRefRequestsFromNotes,
  resolveCodeRefs,
} from "../code-refs.js";
import { DEFAULT_CODE_REFS_FILE, type LoadConfigOptions, loadConfig } from "../config.js";
import type { SqliteConnection } from "../db/connection.js";
import { formatIndexErrors, validateVaultNotes } from "../frontmatter.js";
import type { Embedder } from "../search/embedder.js";
import type { BuildIndexResult, Note, ResolvedCodeRef, ResolvedConfig } from "../types.js";
import { readVault } from "../vault.js";

type IndexBuildSummary = {
  mode: "full" | "incremental";
  ftsOnly: boolean;
  notesIndexed: number;
  notesRemoved: number;
  noteCount: number;
  chunkCount: number;
  legacyMigrationNotice: boolean;
};

export type IndexCommandResult = {
  /** SQLite index location, or undefined when `search.enabled` is false (no DB is built). */
  db?: BuildIndexResult;
  /** Operational CLI data kept separate from the deliberately small public index result. */
  build?: IndexBuildSummary;
  outFile: string;
  codeRefsFile: string;
  noteCount: number;
};

export type IndexCommandOptions = {
  full?: boolean;
  embedder?: Embedder;
};

type InternalIndexCommandOptions = IndexCommandOptions & { connection?: SqliteConnection };

export async function runIndex(
  options: LoadConfigOptions & IndexCommandOptions = {},
): Promise<IndexCommandResult> {
  const { full, embedder, ...loadOptions } = options;
  return indexResolved(loadConfig(loadOptions), { full, embedder });
}

export async function indexResolved(
  config: ResolvedConfig,
  options: IndexCommandOptions = {},
): Promise<IndexCommandResult> {
  return indexResolvedInternal(config, options);
}

/** @internal Test seam for exercising multiple index commands on one transaction owner. */
export async function indexResolvedWithConnection(
  config: ResolvedConfig,
  connection: SqliteConnection,
  options: IndexCommandOptions = {},
): Promise<IndexCommandResult> {
  return indexResolvedInternal(config, { ...options, connection });
}

async function indexResolvedInternal(
  config: ResolvedConfig,
  options: InternalIndexCommandOptions,
): Promise<IndexCommandResult> {
  const { full, embedder, connection } = options;

  // Keep search-disabled indexing database-free: it writes only HIERARCHY.md and code-refs.json.
  let db: BuildIndexResult | undefined;
  let build: IndexBuildSummary | undefined;
  if (config.search.enabled) {
    const { buildIndex, buildIndexWithConnection } = await import("../db/indexer.js");
    const result = connection
      ? await buildIndexWithConnection(connection, config, { full }, { embedder })
      : await buildIndex(config, { full }, { embedder });
    db = { indexPath: result.indexPath };
    build = {
      mode: result.mode,
      ftsOnly: result.ftsOnly,
      notesIndexed: result.notesIndexed,
      notesRemoved: result.notesRemoved,
      noteCount: result.noteCount,
      chunkCount: result.chunkCount,
      legacyMigrationNotice: result.legacyMigrationNotice,
    };
  }

  // The DB build (when it ran) already validated the vault and threw on any error, so reaching
  // this point with invalid notes is impossible; re-validation stays only so a search-disabled
  // run reports the same failures `check` would.
  const { validNotes, resolved } = readValidNotesAndCodeRefs(config);

  const outFile = writeHierarchyMd(config, validNotes);
  const codeRefsFile = writeCodeRefsJson(config, resolved);

  return { db, build, outFile, codeRefsFile, noteCount: validNotes.size };
}

function readValidNotesAndCodeRefs(config: ResolvedConfig): {
  validNotes: Map<string, Note>;
  resolved: ResolvedCodeRef[];
} {
  const { notes } = readVault(config.vaultDir);
  const { validNotes, errors } = validateVaultNotes(notes);
  if (errors.length > 0) {
    throw new Error(formatIndexErrors(errors));
  }

  const collected = collectCodeRefRequestsFromNotes(validNotes, new Set(validNotes.keys()));
  const codeRefs = resolveCodeRefs(collected.requests, config.repoRoot);
  const codeRefErrors = [...collected.errors, ...codeRefs.errors];
  if (codeRefErrors.length > 0) {
    throw new Error(formatIndexErrors(codeRefErrors.map((error) => error.message)));
  }
  return { validNotes, resolved: codeRefs.resolved };
}

function writeHierarchyMd(config: ResolvedConfig, notes: Map<string, Note>): string {
  const rows = [...notes.values()].sort((a, b) => {
    if (a.id === "root") return -1;
    if (b.id === "root") return 1;
    return a.id.localeCompare(b.id);
  });
  const outFile = resolve(config.vaultDir, config.index.file);
  const lines = [
    "<!-- AUTOGENERATED by @madebywild/semantic-layer. Do not edit by hand. -->",
    "",
    "# Vault hierarchy",
    "",
    "Agents: read this file first, then load notes by id.",
    "",
    "Sizes are rough token estimates (chars/4). For large notes, prefer",
    '`semantic-layer search "<query>" --json` to load only the matching section.',
    "",
    ...rows.map((note) => {
      const depth = note.id === "root" ? 0 : note.id.split(".").length - 1;
      const status = note.fm.status === "active" ? "" : ` (${note.fm.status})`;
      // Rough token estimate from body length (frontmatter excluded): ~4 chars per token.
      const size = `(~${Math.ceil(note.body.length / 4)} tok)`;
      return `${"  ".repeat(depth)}- **${note.id}**${status} - ${note.fm.title}. ${note.fm.desc} ${size}`;
    }),
  ];
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, `${lines.join("\n")}\n`);
  return outFile;
}

function writeCodeRefsJson(config: ResolvedConfig, resolved: ResolvedCodeRef[]): string {
  const codeRefsFile = resolve(
    config.vaultDir,
    config.index.codeRefsFile ?? DEFAULT_CODE_REFS_FILE,
  );
  mkdirSync(dirname(codeRefsFile), { recursive: true });
  writeFileSync(codeRefsFile, `${JSON.stringify(buildCodeRefsIndex(resolved), null, 2)}\n`);
  return codeRefsFile;
}
