import type { Connection } from "@ladybugdb/core";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  buildCodeRefsIndex,
  collectCodeRefRequestsFromNotes,
  resolveCodeRefs,
} from "../code-refs.js";
import { DEFAULT_CODE_REFS_FILE, loadConfig, type LoadConfigOptions } from "../config.js";
import { formatIndexErrors, validateVaultNotes } from "../frontmatter.js";
import type { Embedder } from "../search/embedder.js";
import type { BuildIndexResult, Note, ResolvedCodeRef, ResolvedConfig } from "../types.js";
import { readVault } from "../vault.js";

export type IndexCommandResult = {
  /** The LadybugDB build result, or undefined when `search.enabled` is false (no DB is built). */
  db?: BuildIndexResult;
  outFile: string;
  codeRefsFile: string;
  noteCount: number;
};

export type IndexCommandOptions = {
  full?: boolean;
  embedder?: Embedder;
  /** Dependency-injection seam for tests that need to reuse an open connection. */
  connection?: Connection;
};

export async function runIndex(
  options: LoadConfigOptions & IndexCommandOptions = {},
): Promise<IndexCommandResult> {
  const { full, embedder, connection, ...loadOptions } = options;
  return indexResolved(loadConfig(loadOptions), { full, embedder, connection });
}

export async function indexResolved(
  config: ResolvedConfig,
  options: IndexCommandOptions = {},
): Promise<IndexCommandResult> {
  const { full, embedder, connection } = options;

  // The db module chain loads LadybugDB's native binding, so it is imported lazily and only when
  // search is enabled — `check`/`init`/`refine` and a search-disabled `index` must keep working
  // on platforms where the native module is unavailable (e.g. musl/Alpine).
  let db: BuildIndexResult | undefined;
  if (config.search.enabled) {
    const { buildIndex, buildIndexWithConnection } = await import("../db/indexer.js");
    db = connection
      ? await buildIndexWithConnection(connection, config, { full }, { embedder })
      : await buildIndex(config, { full }, { embedder });
  }

  // The DB build (when it ran) already validated the vault and threw on any error, so reaching
  // this point with invalid notes is impossible; re-validation stays only so a search-disabled
  // run reports the same failures `check` would.
  const { validNotes, resolved } = readValidNotesAndCodeRefs(config);

  const outFile = writeHierarchyMd(config, validNotes);
  const codeRefsFile = writeCodeRefsJson(config, resolved);

  return { db, outFile, codeRefsFile, noteCount: validNotes.size };
}

function readValidNotesAndCodeRefs(config: ResolvedConfig): {
  validNotes: Map<string, Note>;
  resolved: ResolvedCodeRef[];
} {
  const { notes } = readVault(config.vaultDir);
  const { validNotes, errors } = validateVaultNotes(notes);
  if (errors.length > 0) {
    throw new Error(formatIndexErrors(errors));
  }

  const collected = collectCodeRefRequestsFromNotes(validNotes, new Set(validNotes.keys()));
  const codeRefs = resolveCodeRefs(collected.requests, config.repoRoot);
  const codeRefErrors = [...collected.errors, ...codeRefs.errors];
  if (codeRefErrors.length > 0) {
    throw new Error(formatIndexErrors(codeRefErrors.map((error) => error.message)));
  }
  return { validNotes, resolved: codeRefs.resolved };
}

function writeHierarchyMd(config: ResolvedConfig, notes: Map<string, Note>): string {
  const rows = [...notes.values()].sort((a, b) => {
    if (a.id === "root") return -1;
    if (b.id === "root") return 1;
    return a.id.localeCompare(b.id);
  });
  const outFile = resolve(config.vaultDir, config.index.file);
  const lines = [
    "<!-- AUTOGENERATED by @madebywild/semantic-layer. Do not edit by hand. -->",
    "",
    "# Vault hierarchy",
    "",
    "Agents: read this file first, then load notes by id.",
    "",
    ...rows.map((note) => {
      const depth = note.id === "root" ? 0 : note.id.split(".").length - 1;
      const status = note.fm.status === "active" ? "" : ` (${note.fm.status})`;
      return `${"  ".repeat(depth)}- **${note.id}**${status} - ${note.fm.title}. ${note.fm.desc}`;
    }),
  ];
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, `${lines.join("\n")}\n`);
  return outFile;
}

function writeCodeRefsJson(config: ResolvedConfig, resolved: ResolvedCodeRef[]): string {
  const codeRefsFile = resolve(
    config.vaultDir,
    config.index.codeRefsFile ?? DEFAULT_CODE_REFS_FILE,
  );
  mkdirSync(dirname(codeRefsFile), { recursive: true });
  writeFileSync(codeRefsFile, `${JSON.stringify(buildCodeRefsIndex(resolved), null, 2)}\n`);
  return codeRefsFile;
}
